from core.runtime_paths import DEBUG_DATA_DIR, RAW_DATA_DIR, STATE_DATA_DIR

RAW_DIR = RAW_DATA_DIR
STATE_DIR = STATE_DATA_DIR
DEBUG_DIR = DEBUG_DATA_DIR

CASAFARI_SOURCE_NAME = "casafari_history"

CASAFARI_HISTORY_BASE_URL = (
    "https://es.casafari.com/account/history"
    "?id=69b2e8049d0bcd0883a01c4f"
    "&historyType=new"
    "&from=2026-02-11T00:00:00.000Z"
    "&to=2026-03-12T16:28:14.189Z"
    "&sort=sort-by-date-high-to-low"
    "&direct=true"
)

CASAFARI_STORAGE_STATE_PATH = STATE_DIR / "casafari_storage_state.json"
CASAFARI_VERIFIED_HISTORY_URL_PATH = STATE_DIR / "casafari_verified_history_url.txt"
CASAFARI_PROFILE_DIR = STATE_DIR / "casafari_profile"

CASAFARI_DEBUG_BASE_DIR = DEBUG_DIR
for path in (CASAFARI_DEBUG_BASE_DIR, CASAFARI_PROFILE_DIR):
    path.mkdir(parents=True, exist_ok=True)

CASAFARI_HEADLESS = False
CASAFARI_SYNC_OVERLAP_HOURS = 24
CASAFARI_MAX_PAGES_PER_SYNC = 40
CASAFARI_WAIT_AFTER_GOTO_MS = 4000
CASAFARI_WAIT_AFTER_PAGINATION_MS = 2500
CASAFARI_WAIT_BETWEEN_PAGE_CHECKS_MS = 700
CASAFARI_PAGE_CHANGE_MAX_WAIT_MS = 10000
CASAFARI_BOOTSTRAP_DAYS = 3
